### ISSUE TITLE
Add FloorAdjuster

### ISSUE THREAD

**Issue by Sayamame-beans** [Spokeek/awesome-ndmf#3]
https://github.com/Narazaka/FloorAdjuster is a NDMF based tool to adjust avatar's vertical position.
It should be able to be used to prevent the avatar's feet from getting buried in the floor or to float the avatar. (I am not the main user, so I only know of the former usage.)

**Comment by Spokeek** [comment]
True, didn't though about it while it's made by Narazaka. Will add, thank you.

**Comment by Spokeek** [comment]
Added Thanks again
